
devices:
  device_name_1:                #you can name this tag how you want like "when pigs fly"
    interface: /dev/tty1        #your serial interface
    baud: 9600                  #your baud rate
    bucket: my_bucket           # your influxdb2 bucket
    org: my_org                 # your influxdb2 org
    token: my_token             # your token, choose wisely. A good token for this program CAN ONLY WRITE to the your bucket!         
    url: https://your_influxdb_server.org
    port: 12345                 # when using the default 8086 port for influx db, this tag can be obmitted
